### PR TITLE
Some fixes.

### PR DESCRIPTION
**Pull request by stefanwayon**
Added encoding to WSUrlFetch.newRequest() and fixed the code for the scenario when a user requests "offline_access" and facebook does not send an expiry time.

### CODE REVIEW

**Comment by 0xRoch** [comment]
thanks

**Comment by jagregory** [comment]
It'd be good to see this merged, as right now fbconnect doesn't work out of the box with Play! 1.2.*.

**Comment by ngirardin** [comment]
+1, makes it send to push to heroku...

**Comment by mmurray** [comment]
Sorry that took so long.. been really busy :) I'll try to keep an eye on this.

**Comment by ngirardin** [comment]
Thank you very much for the quick response and action! :)

**Pull request merged**
